### ISSUE TITLE
TypeError: Cannot read property 'uHash' of undefined

### ISSUE THREAD

**Issue by Code-Log** [Code-Log/schyfts-backend#1]
Log event:

TypeError: Cannot read property 'uHash' of undefined
    at Query.<anonymous> (/workspace/index.js:808:30)
    at Query.<anonymous> (/workspace/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/workspace/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/workspace/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/workspace/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
    at Query.EofPacket (/workspace/node_modules/mysql/lib/protocol/sequences/Query.js:133:8)
    at Protocol._parsePacket (/workspace/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/workspace/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/workspace/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/workspace/node_modules/mysql/lib/protocol/Protocol.js:38:16)

**Comment by Code-Log** [comment]
[downloaded-logs-20210426-133730.csv](https://github.com/Code-Log/schyfts-backend/files/6376724/downloaded-logs-20210426-133730.csv)

**Comment by Code-Log** [comment]
insertId,labels.clone_id,logName,receiveTimestamp,resource.labels.module_id,resource.labels.project_id,resource.labels.version_id,resource.labels.zone,resource.type,severity,textPayload,timestamp
60801c5200092e3461369017,00c61b117cb005c89c08beb29767355b8dba5f5eda7b907bfe62285b532cd09bc98e9db3cc2778bcec2f3ed6faeca6e7f1e82b727993aa2efd53fff005bc071eafed20415705,projects/schyfts/logs/stderr,2021-04-21T12:36:34.820120931Z,default,schyfts,20210316t120416,us12,gae_app,ERROR,"TypeError: Cannot read property 'uHash' of undefined
    at Query.<anonymous> (/workspace/index.js:808:30)
    at Query.<anonymous> (/workspace/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/workspace/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/workspace/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/workspace/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
    at Query.EofPacket (/workspace/node_modules/mysql/lib/protocol/sequences/Query.js:133:8)
    at Protocol._parsePacket (/workspace/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/workspace/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/workspace/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/workspace/node_modules/mysql/lib/protocol/Protocol.js:38:16)",2021-04-21T12:36:34.601652Z
60801c4d000affdbe3dd0a12,00c61b117ccf645b229511c70a445dc137d887fa28f15eb6e34d1589d54aa5db6a0d480398eac1f2d610c16db16065c95bcd06b47f9a83b73db6e88ac2c5855d8aa8f520aa97,projects/schyfts/logs/stderr,2021-04-21T12:36:29.823494991Z,default,schyfts,20210316t120416,us12,gae_app,ERROR,"TypeError: Cannot read property 'uHash' of undefined
    at Query.<anonymous> (/workspace/index.js:808:30)
    at Query.<anonymous> (/workspace/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/workspace/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/workspace/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/workspace/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
    at Query.EofPacket (/workspace/node_modules/mysql/lib/protocol/sequences/Query.js:133:8)
    at Protocol._parsePacket (/workspace/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/workspace/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/workspace/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/workspace/node_modules/mysql/lib/protocol/Protocol.js:38:16)",2021-04-21T12:36:29.720859Z
